<div class="row dash-row">
  <div class="col-md-3 dash-header hidden-xs hidden-sm" ng-controller="NavController as nav">

    <nav id="library">
      <h4>My Library</h4>
      <ul class="list-unstyled schools">
        <li id="welcome" class="dash-nav">
          <a class="text-left" href="/dashboard">
            <div class="iconBox">
              <i class="icon front icon_rate_1"></i>
              <i class="icon back icon_rate_2"></i>
            </div>
            <span>Welcome</span>
          </a>
        </li>
        <li id="saved" class="dash-nav">
          <a class="text-left" href="/dashboard/saved">
            <div class="iconBox">
              <i class="icon front icon_folder_1"></i>
              <i class="icon back icon_folder_2"></i>
            </div>
            <span>Saved</span>
          </a>
        </li>
        <li id="viewed" class="dash-nav">
          <a class="text-left" href="/dashboard/viewed">
            <div class="iconBox">
              <i class="icon front icon_recent_1"></i>
              <i class="icon back icon_recent_2"></i>
            </div>
            <span>Viewed</span>
          </a>
        </li>
        <li id="contribute" class="dash-nav">
          <a class="text-left" href="/dashboard/uploads">
            <div class="iconBox">
              <i class="icon front icon_upload_1"></i>
              <i class="icon back icon_upload_2"></i>
            </div>
            <span>My Uploads</span>
          </a>
        </li>
      </ul>

    </nav>

    <nav id="personal">
      <h4>Personal</h4>
      <ul class="list-unstyled schools">
        <li class="dash-nav" ng-class="nav.isSubRoute('settings') ? 'active' : ''">
          <a class="text-left" ui-sref="settings">
            <div class="iconBox">
              <i class="icon front icon_settings_1"></i>
              <i class="icon back icon_settings_2"></i>
            </div>
            <span>Account Settings</span>
          </a>
        </li>
        <li class="dash-nav" ng-class="nav.isSubRoute('profile') ? 'active' : ''">
          <a class="text-left" ui-sref="profile">
            <div class="iconBox">
              <i class="icon front icon_profile_1"></i>
              <i class="icon back icon_profile_2"></i>
            </div>
            <span>Profile</span>
          </a>
        </li>
        <li class="dash-nav" ng-class="nav.isSubRoute('messages') ? 'active' : ''">
          <a class="text-left" ui-sref="messages">
            <div class="iconBox">
              <i class="icon front icon_email_1"></i>
              <i class="icon back icon_email_2"></i>
            </div>
            <span>Messages</span>

            <p class="badge label-danger js-unread-msg"></p>
          </a>
        </li>
      </ul>

    </nav>

  </div>

  <div class="col-lg-9 col-md-9 dash-body">

    <ui-view></ui-view>

  </div>
</div>
